trigger:
- publish

pool:
  vmImage: 'ubuntu-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  displayName: Pack https
  inputs:
    command: pack
    publishWebProjects: false
    packagesToPack: '**/https.csproj'
    configuration: $(buildConfiguration)
    packDirectory: $(build.ArtifactStagingDirectory)
    versioningScheme: byPrereleaseNumber
    majorVersion: 0
    minorVersion: 2
    patchVersion: 0

- task: DotNetCoreCLI@2
  displayName: Test https
  inputs:
    command: test
    projects: '**/https.Tests.csproj'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(build.ArtifactStagingDirectory)'
    ArtifactName: 'https'
    Parallel: true

